name: build and deploy release
on:
  release:
    types: [published]
jobs:
  build:
    if: github.repository == 'QW-Group/qwfwd'
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: linux-amd64
            triple: x86_64-unknown-linux-gnu
            os: linux
            arch: amd64
            ext: ""
          - target: linux-i686
            triple: i686-unknown-linux-gnu
            os: linux
            arch: i686
            ext: ""
          - target: linux-armhf
            triple: armv7-unknown-linux-gnueabihf
            os: linux
            arch: armhf
            ext: ""
          - target: linux-aarch64
            triple: aarch64-unknown-linux-gnu
            os: linux
            arch: aarch64
            ext: ""
          - target: windows-x64
            triple: x86_64-pc-windows-gnu
            os: windows
            arch: x64
            ext: ".exe"
          - target: windows-x86
            triple: i686-pc-windows-gnu
            os: windows
            arch: x86
            ext: ".exe"
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
      - name: Install cross
        run: cargo install cross --locked
      - name: Build
        run: cross build --release --target ${{ matrix.triple }}
      - name: Create checksum
        run: |
             md5sum target/${{ matrix.triple }}/release/qwfwd${{ matrix.ext }} > target/${{ matrix.triple }}/release/qwfwd.md5
      - name: Setup SSH
        shell: bash
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          ssh-agent -a $SSH_AUTH_SOCK > /dev/null
          ssh-add - <<< "${{ secrets.SSH_PRIVATE_KEY }}"
      - name: Set date
        shell: bash
        run: |
          echo "DATE=$(TZ="Europe/Amsterdam" date "+%Y%m%d-%H%M%S")" >> $GITHUB_ENV
      - name: Deploy
        shell: bash
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
             BIN=target/${{ matrix.triple }}/release
             mkdir -p upload/releases/${{ github.ref_name }}/${{ matrix.os }}/${{ matrix.arch }}
             mkdir -p upload/releases/latest/${{ matrix.os }}/${{ matrix.arch }}
             cp $BIN/qwfwd${{ matrix.ext }} upload/releases/${{ github.ref_name }}/${{ matrix.os }}/${{ matrix.arch }}/qwfwd${{ matrix.ext }}
             cp $BIN/qwfwd.md5 upload/releases/${{ github.ref_name }}/${{ matrix.os }}/${{ matrix.arch }}/qwfwd.md5
             cp $BIN/qwfwd${{ matrix.ext }} upload/releases/latest/${{ matrix.os }}/${{ matrix.arch }}/qwfwd${{ matrix.ext }}
             cp $BIN/qwfwd.md5 upload/releases/latest/${{ matrix.os }}/${{ matrix.arch }}/qwfwd.md5
             sftp -rp -o 'StrictHostKeyChecking no' -o 'UserKnownHostsFile /dev/null' -P ${{ secrets.SFTP_PORT }} ${{ secrets.SFTP_USERNAME }}@${{ secrets.SFTP_HOST }}:/releases <<< $'put -rp upload/releases/*'
